name: CI - Testes e Cobertura

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  run-tests-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.11.1"
          cache: "npm"

      - name: Instalar Dependências
        run: npm ci

      - name: Executar Testes e Cobertura
        id: coverage
        run: npm run test:coverage

      - name: Publicar Comentário de Cobertura
        uses: MishaKav/jest-coverage-comment@main
        if: always()
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          title: "Relatório de Cobertura de Testes"
          summary-title: "Resumo"
          badge-title: "Cobertura"
          hide-summary: false
          create-new-comment: false
          junitxml-title: "Resultados dos Testes"
